security:
    encoders:
        bcrypt:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern:  ^/api/doc
            stateless: true
            anonymous: true

        api_signup:
            pattern:  ^/api/signup
            stateless: true
            anonymous: true


    access_control:
        - { path: ^/profile/*,   roles: ROLE_USER                    }
        - { path: ^/api/doc,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/,        roles: IS_AUTHENTICATED_ANONYMOUSLY }
